// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import StartRitualReducer from "../start_ritual_reducer";
import SubmitMessageReducer from "../submit_message_reducer";

export type StartRitualParams = __Infer<typeof StartRitualReducer>;
export type SubmitMessageParams = __Infer<typeof SubmitMessageReducer>;

