// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveRitual = __t.object("ActiveRitual", {
  userId: __t.identity(),
  ancestorThreadId: __t.u64(),
  descendantThreadId: __t.u64(),
  currentStep: __t.u32(),
  stability: __t.i32(),
  x: __t.f32(),
  y: __t.f32(),
});
export type ActiveRitual = __Infer<typeof ActiveRitual>;

export const FinalBreath = __t.object("FinalBreath", {
  id: __t.u64(),
  threadId: __t.u64(),
  finalWords: __t.string(),
  clarityScore: __t.u32(),
  timestamp: __t.timestamp(),
});
export type FinalBreath = __Infer<typeof FinalBreath>;

export const GhostMessage = __t.object("GhostMessage", {
  messageId: __t.u64(),
  threadId: __t.u64(),
  stepIndex: __t.u32(),
  text: __t.string(),
});
export type GhostMessage = __Infer<typeof GhostMessage>;

export const GhostThread = __t.object("GhostThread", {
  threadId: __t.u64(),
  isComplete: __t.bool(),
  totalSteps: __t.u32(),
});
export type GhostThread = __Infer<typeof GhostThread>;

export const Gravestone = __t.object("Gravestone", {
  threadId: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  finalWords: __t.string(),
  clarityScore: __t.u32(),
});
export type Gravestone = __Infer<typeof Gravestone>;

export const RitualCancelled = __t.object("RitualCancelled", {
  id: __t.u64(),
  userId: __t.identity(),
  timestamp: __t.timestamp(),
  descendantThreadId: __t.option(__t.u64()),
});
export type RitualCancelled = __Infer<typeof RitualCancelled>;

